# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend Deployment

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: echo 'Starting building...'
    - run: npm run build
    - run: echo 'Done!'
    - run: echo 'Moving files via secure shell ...'
    - run: scp -r  ./dist/* root@204.48.26.219:/var/www/peoplepilot.com.br/html 
    - run: echo 'Done!'
    - run: echo 'Deployed successfully!'

    
